apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudprober2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudprober2
  template:
    metadata:
      annotations:
        checksum/config: "${CONFIG_CHECKSUM}"
      labels:
        app: cloudprober2
    spec:
      volumes:
      - name: cloudprober2-config
        configMap:
          name: cloudprober2-config
      containers:
      - name: cloudprober2
        image: cloudprober/cloudprober
        command: ["/cloudprober"]
        args: [
          "--config_file","/cfg/cloudprober.cfg",
          "--logtostderr"
        ]
        volumeMounts:
        - name: cloudprober2-config
          mountPath: /cfg
        ports:
        - name: http
          containerPort: 9313
---
apiVersion: v1
kind: Service
metadata:
  name: cloudprober2
  labels:
    app: cloudprober2
spec:
  ports:
  - port: 9313
    protocol: TCP
    targetPort: 9313
  selector:
    app: cloudprober2
  type: NodePort
